apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pepega-react-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: pepega-react.k8s-example.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pepega-react
                port:
                  number: 80
