stages:
  - build-docker
  - deploy

variables:
  DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

build-docker:
  stage: build-docker
  image: docker:23-git
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_TAG

deploy:
  stage: deploy
  image: alpine/helm:3.8.0
  script:
    - helm create charts/pepega-react
    - helm install pepega-react charts/pepega-react
    - kubectl apply -f charts/pepega-react/templates/deployment.yaml
    - kubectl apply -f charts/pepega-react/templates/service.yaml
    - kubectl apply -f charts/pepega-react/templates/ingress.yaml
